### ISSUE TITLE
Generating font ROMs

### ISSUE THREAD

**Issue by riktw** [AndresNavarro82/vt52-fpga#2]
Hello, 

In the project there are two generated fonts, I am curious how they where generated. From what I can tell, the bdf files are a subset of the terminus 8*16 fonts, and from those the .hex files are generated.
Is there instructions or a script available how this was done? That could help in using different fonts or such changes.

Best regards,
Rik

**Comment by AndresNavarro82** [comment]
I made them on the spot with some emacs macros, but a script to do that should be easy enough: the formats are pretty similar. It's mostly just deleting and rearranging lines.  I'll see if I can write something over the weekend

**Comment by DavidJRichards** [comment]
Greetings Andres, I would like to have a binary version of the font with line drawing characters available in the lower 256 glyphs. I see the bdf font file has these characters but as much higher number characters. I have little experience with font manipulation needed to convert from the bdf to hex format, any pointers to help doing so greatly appreciated. Kind regards, David.

**Comment by AndresNavarro82** [comment]
I am writing a small script to automate this as we speak, stay tuned...

**Comment by AndresNavarro82** [comment]
Just added a python script to the mem directory to generate hex files for new font roms from a bdf file and a codepoint mapping.  It's not production ready at all, but should give anybody interested enough to generate custom roms. I tested it with the provided terminus font and it generates the exact same .hex files I made manually.  Not tested any further.  

If you use it, please let me know if it helped.

I don't intend to work more on this script, but I will gladly accept either bug reports of the current functionality or pull requests with added features if anybody wants to extend it/clean it up (like adding command-line arguments, maps in external files instead of python dicts, documentation, etc)

**Comment by DavidJRichards** [comment]
Thanks Andres, I shall now attempt to implement vt52 alternative character
set feature. Kind regards, David.
